name 'formatron_elasticsearch'
version '0.1.1'
description 'Formatron Elasticsearch cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/elasticsearch-cookbook'
issues_url 'https://github.com/formatron/elasticsearch-cookbook/issues'
supports 'ubuntu'
depends 'apt'
